name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  id-token: write
  issues: write
  repository-projects: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
      version: ${{ steps.release.outputs.version }}
    steps:
      - name: Run release-please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  build-and-publish:
    if: needs.release-please.outputs.release_created
    needs: release-please
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore src/SolarScope.csproj

      - name: Update version in csproj
        run: |
          VERSION="${{ needs.release-please.outputs.version }}"
          sed -i "s/<PackageVersion>.*<\/PackageVersion>/<PackageVersion>$VERSION<\/PackageVersion>/" src/SolarScope.csproj

      - name: Update version in README.md badge/link
        run: |
          VERSION="${{ needs.release-please.outputs.version }}"
          sed -i "s|/packages/SolarScope/[0-9.]*|/packages/SolarScope/$VERSION|g" README.md      # --------- Inject release notes step (NEW) ----------

      - name: Commit and push version/badge updates
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add src/SolarScope.csproj README.md
          git commit -m "chore: update version and badge in csproj and README.md [skip ci]" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Inject release notes into csproj
        run: |
          VERSION="${{ needs.release-please.outputs.version }}"

          # Extract release notes for this version from CHANGELOG.md
          RELEASE_NOTES=$(awk "/^## \\[$VERSION\\]/ {flag=1; next} /^## \\[/ {flag=0} flag" CHANGELOG.md | sed '/^$/d')

          # Escape special XML chars for csproj
          ESCAPED_NOTES=$(echo "$RELEASE_NOTES" | sed 's/&/\&amp;/g; s/</\&lt;/g; s/>/\&gt;/g')

          # Replace or add the PackageReleaseNotes element in the csproj
          if grep -q "<PackageReleaseNotes>" src/SolarScope.csproj; then
            # Replace content between tags
            sed -i "/<PackageReleaseNotes>/,/<\/PackageReleaseNotes>/c\<PackageReleaseNotes>$ESCAPED_NOTES</PackageReleaseNotes>" src/SolarScope.csproj
          else
            # Add after <PropertyGroup>
            sed -i "/<PropertyGroup>/a \  <PackageReleaseNotes>$ESCAPED_NOTES</PackageReleaseNotes>" src/SolarScope.csproj
          fi

          # Save release notes for later use in NuGet push (for GitHub Actions output)
          echo "RELEASE_NOTES<<EOF" >> $GITHUB_ENV
          echo "$RELEASE_NOTES" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Commit release notes update
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add src/SolarScope.csproj
          git commit -m "chore: update release notes in csproj for v${{ needs.release-please.outputs.version }} [skip ci]" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: dotnet build src/SolarScope.csproj --configuration Release --no-restore

      - name: Test
        run: dotnet test src/SolarScope.csproj --configuration Release --no-build --verbosity normal
        continue-on-error: true  # Continue even if no tests are found

      - name: Pack
        run: dotnet pack src/SolarScope.csproj --configuration Release --no-build --output ./artifacts

      - name: Verify package metadata
        run: |
          echo "Verifying package contains release notes..."
          # Extract and display the PackageReleaseNotes from csproj to confirm they were added
          grep -A5 -B5 "PackageReleaseNotes" src/SolarScope.csproj || echo "No PackageReleaseNotes found in csproj"
          
          # List the generated package
          ls -la ./artifacts/

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nuget-package
          path: ./artifacts/*.nupkg

      - name: Publish to NuGet
        run: |
          echo "Publishing to NuGet with release notes:"
          echo "----------------------------------------"
          echo "$RELEASE_NOTES"
          echo "----------------------------------------"
          
          # Push to NuGet (release notes are embedded in the package via PackageReleaseNotes in csproj)
          dotnet nuget push ./artifacts/*.nupkg \
            --api-key ${{ secrets.NUGET_API_KEY }} \
            --source https://api.nuget.org/v3/index.json \
            --skip-duplicate \
            --timeout 300
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}

      - name: Upload packages to release
        run: |
          echo "Uploading packages to GitHub release..."
          echo "Release notes for this version:"
          echo "================================"
          echo "$RELEASE_NOTES"
          echo "================================"
          
          # Upload the NuGet package to the GitHub release
          gh release upload ${{ needs.release-please.outputs.tag_name }} ./artifacts/*.nupkg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
